apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-prd
spec:
  source:
    helm:
      values: |
        podLabels:
          environment: prd
    targetRevision: "v1.6.1"
