apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: apps
  namespace: apps
spec:
  interval: 30m
  url:  https://github.com/LovelaceEngineering/gitops.git
  ref:
    branch: main