apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dev
spec:
  source:
    helm:
      values: |
        podLabels:
          environment: dev
    targetRevision: "v1.6.1"
