apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-dev
  namespace: infra
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/clusters/dev/infra/overlays #apps/bgd/overlays/bgdk
    repoURL: https://github.com/ams0/flux-multicluster-example
    targetRevision: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true