apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-local
  namespace: argocd
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-local
  source:
    path: argocd/clusters/local/infra/overlays #apps/bgd/overlays/bgdk
    repoURL: https://github.com/ams0/flux-multicluster-example
    targetRevision: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true