apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      values: |
        podLabels:
          promtail: "true"
        rbac:
          pspEnabled: false
        config:
          limits_config:
            ingestion_burst_size_mb: 16
            ingestion_rate_mb: 16
            max_streams_per_user: 100000
        serviceMonitor:
          enabled: true
          interval: "30s"
          additionalLabels:
            release: kube-prometheus
        persistence:
          enabled: true
          existingClaim: loki-blob
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: loki-auth
            nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - promtail'
            cert-manager.io/cluster-issuer: vault-clusterissuer
          hosts:
            - host: loki.hub.analytics.atradiusnet.com
              paths:
              - /
          tls:
            - secretName: loki.hub.analytics.atradiusnet.com
              hosts:
                - loki.hub.analytics.atradiusnet.com
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "2.8.4"
    chart: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
