apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
- ns.yaml
- ../../../infra/cert-manager 
patchesStrategicMerge:
  - values/cert-manager/cert-manager-values.yaml