apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/infra/cert-manager/
  - ../../../bases/infra/keycloak/
  - ../../../bases/infra/nats/
  - ../../../bases/infra/traefik/
patchesStrategicMerge:
  - values/cert-manager/cert-manager-values.yaml 
  - values/keycloak/keycloak-values.yaml 
  - values/nats/nats-values.yaml 
  - values/nats/stan-values.yaml
  - values/traefik/traefik-values.yaml 