apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  releaseName: traefik
  targetNamespace: ingress
  chart:
    spec:
      chart: traefik
      version: "10.9.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress
  interval: 30s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 3
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      access:
        enabled: true
    service:
      enabled: true
      type: LoadBalancer
      # Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
#      annotations:
#        service.beta.kubernetes.io/azure-load-balancer-internal: "true"