apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
  interval: 30s
  upgrade:
    force: true
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    replicaCount: 3
    serviceDiscovery:
      enabled: true