apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: cluster-config
spec:
  releaseName: nats
  targetNamespace: nats
  chart:
    spec:
      chart: nats
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: nats
  interval: 30s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    cluster:
      enabled: true
      replicas: 3