apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cluster-config
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.6.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 30s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true